Get and view post comments
kisanola/tech-community-frontend pull request #10
Opened 2019-10-07 15:23 UTC by gracelungu

#### What does this PR do?
This PR adds the functionality for getting and viewing post comments

#### Description of Task to be completed?
~ Add the `PostComments` component
~ Fetch the post comments within the actions
~ Test the component with its actions

#### How should this be manually tested?
~ Fetch and checkout to `ft-view-comments`
~ Add the `PostComments` components to `Home`
~ Pass the required `Post` props

#### Screenshots (if appropriate)
![image](https://user-images.githubusercontent.com/46924450/66325186-1a8dae80-e927-11e9-9073-6397cf676cb0.png)

#### Questions:
N/A

2019-10-07 18:42 UTC, gracelungu commented
![](https://github.trello.services/images/mini-trello-icon.png) [Users should be able to view comments of a single post](https://trello.com/c/yrRExWHU/57-users-should-be-able-to-view-comments-of-a-single-post)

2019-10-09 08:48 UTC, Karlmusingo approved these changes

2019-10-15 17:08 UTC, nkpremices requested changes

2019-10-15 17:08 UTC, nkpremices commented on src/__tests__/actions/feed.test.js
> +describe('Login actions', () => {
@gracelungu, is this test about login actions ?

2019-10-15 17:08 UTC, nkpremices commented on src/__tests__/actions/postComments.test.js
> +describe('Login actions', () => {
Same here @gracelungu

2019-10-15 21:52 UTC, oesukam commented
@gracelungu Fix conflicts

2019-10-16 00:29 UTC, merged