Add signup page
kisanola/tech-community-frontend pull request #3
Opened 2019-06-28 10:45 UTC by gracelungu

#### What does this PR do?
This PR adds the login page to the platform

#### Description of Task to be completed?
~ Design the login page
~ Handle the login logic
~ Write tests

#### How should this be manually tested?
`/login`

#### Screenshots (if appropriate)
![image](https://user-images.githubusercontent.com/46924450/60337130-7e0c5580-99a2-11e9-91e6-1d00fee1aeb1.png)

![image](https://user-images.githubusercontent.com/46924450/60337147-85cbfa00-99a2-11e9-84a6-ee65b2ae492e.png)

2019-06-30 10:23 UTC, oesukam requested changes

2019-06-30 10:23 UTC, oesukam commented on package.json
> +    "typeface-open-sans": "0.0.54",
@gracelungu Can we use the CDN instead to reduce on the request bundle?

2019-06-30 10:23 UTC, oesukam commented on src/actions/loginActions.js
> +import axios from 'axios';
Can we create the `axios` util for customization?

2019-06-30 10:23 UTC, oesukam commented on src/index.js
> +import 'typeface-open-sans';
Let us use the cdn

2019-06-30 10:23 UTC, oesukam commented on src/pages/Home/Home.jsx
>  export default connect(
You don't need to connect if you are not using the store

2019-06-30 10:23 UTC, oesukam commented on src/pages/Login/Login.jsx
> +  form = React.createRef();
Why the reference?

2019-07-19 12:29 UTC, gracelungu commented on src/pages/Login/Login.jsx
> +  form = React.createRef();
To use HTML5 validation.

2019-07-20 16:17 UTC, merged