Added Scroll Back To Top
kisanola/tech-community-frontend pull request #39
Opened 2020-04-26 11:46 UTC by Yoncity

#### What does this PR do?
This PR adds a button to scroll to the top of the page.

#### Description of Task to be completed?

#### How should this be manually tested?

#### Screenshots (if appropriate)
![Screenshot from 2020-04-26 14-42-41](https://user-images.githubusercontent.com/37688326/80306495-61ac9580-87cc-11ea-8335-faaed90f0e1a.png)
![Screenshot from 2020-04-26 14-42-48](https://user-images.githubusercontent.com/37688326/80306498-65d8b300-87cc-11ea-82b1-623abb1b8e7d.png)

#### Questions:

2020-04-26 12:03 UTC, gracelungu commented
@Yoncity Do you mind reducing the size of the button in half the current size? it looks imposing.

2020-04-26 12:04 UTC, gracelungu commented
@Yoncity Resolve the conflict, be careful while accepting changes.

2020-04-26 12:08 UTC, oesukam requested changes
You can reduce a little bit on the shadow as we are pretty much not using shadows

2020-04-26 12:14 UTC, Yoncity commented
> You can reduce a little bit on the shadow as we are pretty much not using shadows

Reduced it to 1px

2020-04-26 12:15 UTC, Yoncity commented
> @Yoncity Resolve the conflict, be careful while accepting changes.

Reduced to 20 x 20px

2020-04-26 12:31 UTC, oesukam commented on src/pages/Home/Home.jsx
> +            <button
What about other pages?

2020-04-27 13:48 UTC, oesukam requested changes

2020-04-27 13:48 UTC, oesukam commented on src/components/ScrollToTop/ScrollToTop.scss
> +  }
Add new line at the end of the file

2020-04-27 20:00 UTC, Yoncity commented on src/components/ScrollToTop/ScrollToTop.scss
> +  }
Done.

2020-04-27 20:55 UTC, oesukam approved these changes
LGTM

2020-04-27 20:55 UTC, merged