Post textarea component
kisanola/tech-community-frontend pull request #5
Opened 2019-09-04 18:17 UTC by Karlmusingo

Add posting functionality

2019-09-05 13:07 UTC, oesukam requested changes

2019-09-05 13:07 UTC, oesukam commented on .env.example
> +REACT_APP_API_KEY = 478758755655457
Variables should be empty and you don't need space before and after the `=` sign

2019-09-05 13:07 UTC, oesukam commented on .vscode/settings.json
> +}
Blank line required

2019-09-05 13:07 UTC, oesukam commented on package.json
> +    "@webscopeio/react-textarea-autocomplete": "^4.6.1",
Are you using this package?

2019-09-05 13:07 UTC, oesukam commented on src/actionTypes/postTypes.js
> +export const POST_ERROR = 'POST_ERROR';
Blank line required

2019-09-05 13:07 UTC, oesukam commented on src/actions/postActions.js
> +                dispatch(postError('The post should have at least 50 characters long'));
Why are you handling this from the frontend?

2019-09-05 13:07 UTC, oesukam commented on src/actions/postActions.js
> +        dispatch(postError('Please check your internet connection'));
I think this should be reusable instead of implementing it like this including `try and catch`

2019-09-05 13:07 UTC, oesukam commented on src/components/PostTextArea/PostTextArea.scss
> +
Why this space

2019-09-09 07:24 UTC, Karlmusingo commented
![](https://github.trello.services/images/mini-trello-icon.png) [Home page design (Posts)](https://trello.com/c/CN1hqrZs/23-home-page-design-posts)

2019-09-09 10:04 UTC, Karlmusingo commented on package.json
> +    "@webscopeio/react-textarea-autocomplete": "^4.6.1",
No, I am not using it

2019-09-30 14:47 UTC, merged