Share Post implementation
kisanola/tech-community-frontend pull request #9
Opened 2019-10-04 13:54 UTC by Yoncity

**What does this PR do?**
This PR adds the share to social media feature, that enables users to share posts to FaceBook and Twitter

**Description of the task to be completed.**
~ Create SharePost component
~ Create actions that consume the share endpoints
~ Write tests for the component and actions

**How should this be manually tested?**
~ Fetch and checkout to the branch with `git fetch origin ft-share-post && git checkout ft-share-post`
~ Start the server
~ Authenticate with the Google Auth option
~ Press the share icon at the bottom right of any post.

2019-10-04 18:41 UTC, Yoncity commented
![](https://github.trello.services/images/mini-trello-icon.png) [Users should be able to share a post via email, LinkedIn, Facebook and twitter](https://trello.com/c/M6Y7ZG2H/40-users-should-be-able-to-share-a-post-via-email-linkedin-facebook-and-twitter)

2019-10-08 11:48 UTC, gracelungu requested changes

2019-10-08 11:48 UTC, gracelungu commented on src/components/SharePost/SharePost.jsx
> +          </div> */}
@Yoncity Please remove the commented code above

2019-10-08 11:48 UTC, gracelungu commented on src/components/SharePost/SharePost.jsx
> +// const mapStateToProps = state => ({});
This one too

2019-10-09 14:54 UTC, Karlmusingo commented on src/components/SharePost/SharePost.jsx
> +  // LinkedinShareButton,
@Yoncity, would you also add Linkedin even if it is not yet supported by the backend

2019-10-09 15:03 UTC, Karlmusingo commented on src/components/SharePost/SharePost.jsx
> +  postSlug: PropTypes.string,
Also add default value for props which are not required

2019-10-09 15:34 UTC, Karlmusingo commented on src/components/Feed/Feed.jsx
> +  state = {
When there is a constructor, it is better if the state is placed inside the constructor

2019-10-10 07:31 UTC, Karlmusingo approved these changes

2019-10-10 07:34 UTC, gracelungu approved these changes

2019-10-10 07:53 UTC, merged